# config/expanded_news_sources.yaml - Much more diverse source coverage

news_sources:
  left_leaning:
    # Major left-leaning sources
    - name: "CNN"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "cnn"
      bias_score: 0
      tier: "major"
      
    - name: "The Guardian"
      api_endpoint: "https://content.guardianapis.com/search"
      source_id: "the-guardian-uk"
      bias_score: 0
      tier: "major"
      
    - name: "MSNBC"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "msnbc"
      bias_score: 0
      tier: "major"
      
    - name: "NPR"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "npr"
      bias_score: 0
      tier: "major"
      
    - name: "The Washington Post"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "the-washington-post"
      bias_score: 0
      tier: "major"
      
    - name: "The New York Times"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "the-new-york-times"
      bias_score: 0
      tier: "major"
      
    # Additional left sources
    - name: "HuffPost"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "the-huffington-post"
      bias_score: 0
      tier: "secondary"
      
    - name: "Politico"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "politico"
      bias_score: 0
      tier: "secondary"
      
    - name: "The Hill"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "the-hill"
      bias_score: 0
      tier: "secondary"
      
    - name: "Salon"
      rss_feed: "https://www.salon.com/feed/"
      bias_score: 0
      tier: "alternative"
      
    - name: "Mother Jones"
      rss_feed: "https://www.motherjones.com/feed/"
      bias_score: 0
      tier: "alternative"
      
    - name: "The Nation"
      rss_feed: "https://www.thenation.com/feed/"
      bias_score: 0
      tier: "alternative"

    - name: "Jacobin"
      rss_feed: "https://jacobin.com/feed/"
      bias_score: 0
      tier: "alternative"

    - name: "Democracy Now!"
      rss_feed: "https://www.democracynow.org/democracynow.rss"
      bias_score: 0
      tier: "alternative"

    - name: "Common Dreams"
      rss_feed: "https://www.commondreams.org/rss.xml"
      bias_score: 0
      tier: "alternative"

  centrist:
    # Major centrist sources
    - name: "Reuters"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "reuters"
      bias_score: 1
      tier: "major"
      
    - name: "Associated Press"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "associated-press"
      bias_score: 1
      tier: "major"
      
    - name: "BBC News"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "bbc-news"
      bias_score: 1
      tier: "major"
      
    - name: "USA Today"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "usa-today"
      bias_score: 1
      tier: "major"
      
    - name: "CBS News"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "cbs-news"
      bias_score: 1
      tier: "major"
      
    - name: "ABC News"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "abc-news"
      bias_score: 1
      tier: "major"
      
    # International centrist
    - name: "Al Jazeera English"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "al-jazeera-english"
      bias_score: 1
      tier: "international"
      
    - name: "Deutsche Welle"
      rss_feed: "https://rss.dw.com/xml/rss-en-all"
      bias_score: 1
      tier: "international"
      
    - name: "France 24"
      rss_feed: "https://www.france24.com/en/rss"
      bias_score: 1
      tier: "international"

    - name: "Nikkei Asia"
      rss_feed: "https://asia.nikkei.com/rss/feed/nar"
      bias_score: 1
      tier: "international"

    - name: "South China Morning Post"
      rss_feed: "https://www.scmp.com/rss/91/feed"
      bias_score: 1
      tier: "international"

    - name: "The Hindu"
      rss_feed: "https://www.thehindu.com/feeder/default.rss"
      bias_score: 1
      tier: "international"

    - name: "AllAfrica"
      rss_feed: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf"
      bias_score: 1
      tier: "international"

    - name: "El País"
      rss_feed: "https://english.elpais.com/rss/elpais/portada_english.xml"
      bias_score: 1
      tier: "international"
      
    # Financial/Business (generally centrist)
    - name: "Bloomberg"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "bloomberg"
      bias_score: 1
      tier: "business"
      
    - name: "Financial Times"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "financial-times"
      bias_score: 1
      tier: "business"

  right_leaning:
    # Major right-leaning sources
    - name: "Fox News"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "fox-news"
      bias_score: 2
      tier: "major"
      
    - name: "New York Post"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "new-york-post"
      bias_score: 2
      tier: "major"
      
    - name: "Wall Street Journal"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "the-wall-street-journal"
      bias_score: 2
      tier: "major"
      
    - name: "Washington Examiner"
      api_endpoint: "https://newsapi.org/v2/everything"
      source_id: "washington-examiner"
      bias_score: 2
      tier: "major"
      
    # Additional right sources
    - name: "The Daily Wire"
      rss_feed: "https://www.dailywire.com/feeds/rss.xml"
      bias_score: 2
      tier: "alternative"
      
    - name: "Breitbart News"
      rss_feed: "https://feeds.feedburner.com/breitbart"
      bias_score: 2
      tier: "alternative"
      
    - name: "The Federalist"
      rss_feed: "https://thefederalist.com/feed/"
      bias_score: 2
      tier: "alternative"
      
    - name: "National Review"
      rss_feed: "https://www.nationalreview.com/feed/"
      bias_score: 2
      tier: "conservative"
      
    - name: "The Weekly Standard"
      rss_feed: "https://www.weeklystandard.com/rss.xml"
      bias_score: 2
      tier: "conservative"
      
    - name: "American Conservative"
      rss_feed: "https://www.theamericanconservative.com/feed/"
      bias_score: 2
      tier: "conservative"
      
    - name: "Washington Times"
      rss_feed: "https://www.washingtontimes.com/rss/headlines/"
      bias_score: 2
      tier: "secondary"
      
    - name: "New York Sun"
      rss_feed: "https://www.nysun.com/rss.xml"
      bias_score: 2
      tier: "secondary"

    - name: "Townhall"
      rss_feed: "https://townhall.com/rss/"
      bias_score: 2
      tier: "conservative"

    - name: "Newsmax"
      rss_feed: "https://www.newsmax.com/rss/"
      bias_score: 2
      tier: "secondary"

    - name: "Epoch Times"
      rss_feed: "https://www.theepochtimes.com/c-tech/feed"
      bias_score: 2
      tier: "international"

  libertarian:
    - name: "Reason"
      rss_feed: "https://reason.com/feed/"
      bias_score: 3
      tier: "alternative"
      
    - name: "Cato Institute"
      rss_feed: "https://www.cato.org/rss/commentary"
      bias_score: 3
      tier: "think_tank"

    - name: "Mises Institute"
      rss_feed: "https://mises.org/rss.xml"
      bias_score: 3
      tier: "think_tank"

    - name: "FEE (Foundation for Economic Education)"
      rss_feed: "https://fee.org/feed/"
      bias_score: 3
      tier: "think_tank"

  international:
    # Major international sources for global perspective
    - name: "The Times (UK)"
      rss_feed: "https://www.thetimes.co.uk/rss"
      bias_score: 1
      tier: "international"
      
    - name: "The Telegraph (UK)"
      rss_feed: "https://www.telegraph.co.uk/rss.xml"
      bias_score: 2
      tier: "international"
      
    - name: "The Independent (UK)"
      rss_feed: "https://www.independent.co.uk/rss"
      bias_score: 0
      tier: "international"
      
    - name: "Globe and Mail (Canada)"
      rss_feed: "https://www.theglobeandmail.com/arc/outboundfeeds/rss/"
      bias_score: 1
      tier: "international"
      
    - name: "Sydney Morning Herald"
      rss_feed: "https://www.smh.com.au/rss/feed.xml"
      bias_score: 1
      tier: "international"

  topical:
    - name: "TechCrunch"
      rss_feed: "https://techcrunch.com/feed/"
      bias_score: 1
      tier: "business"

    - name: "Wired"
      rss_feed: "https://www.wired.com/feed/rss"
      bias_score: 1
      tier: "alternative"

    - name: "Scientific American"
      rss_feed: "https://www.scientificamerican.com/feed/rss/"
      bias_score: 1
      tier: "alternative"

    - name: "Nature News"
      rss_feed: "https://www.nature.com/subjects/news.rss"
      bias_score: 1
      tier: "alternative"

    - name: "ESPN"
      rss_feed: "https://www.espn.com/espn/rss/news"
      bias_score: 1
      tier: "secondary"

  niche:
    # Climate & Environment
    - name: "Inside Climate News"
      rss_feed: "https://insideclimatenews.org/feed/"
      bias_score: 0
      tier: "alternative"

    - name: "Climate Home News"
      rss_feed: "https://www.climatechangenews.com/feed/"
      bias_score: 0
      tier: "alternative"

    - name: "Yale Environment 360"
      rss_feed: "https://e360.yale.edu/rss"
      bias_score: 0
      tier: "alternative"

    # Health & Medicine
    - name: "Medical News Today"
      rss_feed: "https://www.medicalnewstoday.com/rss"
      bias_score: 1
      tier: "secondary"

    - name: "STAT News"
      rss_feed: "https://www.statnews.com/feed/"
      bias_score: 1
      tier: "secondary"

    - name: "WHO (World Health Organization)"
      rss_feed: "https://www.who.int/feeds/entity/mediacentre/news/en/rss.xml"
      bias_score: 1
      tier: "international"

    # Cybersecurity & Tech Policy
    - name: "Krebs on Security"
      rss_feed: "https://krebsonsecurity.com/feed/"
      bias_score: 1
      tier: "alternative"

    - name: "The Hacker News"
      rss_feed: "https://feeds.feedburner.com/TheHackersNews"
      bias_score: 1
      tier: "alternative"

    - name: "Dark Reading"
      rss_feed: "https://www.darkreading.com/rss.xml"
      bias_score: 1
      tier: "alternative"

# API configurations
api_configs:
  newsapi:
    base_url: "https://newsapi.org/v2/"
    rate_limit: 1000  # requests per day
    requires_key: true
    
  guardian:
    base_url: "https://content.guardianapis.com/"
    rate_limit: 5000  # requests per day
    requires_key: true
    
  rss:
    rate_limit: 100  # requests per hour per feed
    requires_key: false
    cache_duration: 3600  # seconds

# Source quality tiers
source_tiers:
  major: "Primary mainstream sources"
  secondary: "Secondary mainstream sources" 
  alternative: "Alternative/opinion sources"
  business: "Business/financial focus"
  international: "International sources"
  think_tank: "Think tanks and policy institutes"
  conservative: "Conservative publications"

# Collection strategies
collection_strategies:
  comprehensive:
    include_tiers: ["major", "secondary", "business", "international"]
    max_articles_per_source: 50
    
  mainstream_only:
    include_tiers: ["major"]
    max_articles_per_source: 100
    
  alternative_focus:
    include_tiers: ["alternative", "conservative", "think_tank"]
    max_articles_per_source: 30
    
  international:
    include_tiers: ["international", "major"]
    max_articles_per_source: 25
    
